name: Build and publish resume
run-name: Build and publish resume by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - "fonts/**.*"
      - "**.tex"
      - "**.cls"
      - "**.sty"

jobs:
  issue_voucher:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out this updates
        uses: actions/checkout@v3

      - name: Compiling resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          compiler: xelatex
          
      # - name: LS
      #   run: |
      #     ls out
          
      # - name: Copy resume to temp folder
      #   run: |
      #     mkdir -p out\\publish
      #     ls out
      #     cp out\\resume.pdf out\\publish
      #     ls out\\publish
    
      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: my-resume
      #     path: out\\resume.pdf
      #     retention-days: 5
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-resume
          path: out
          retention-days: 5
