name: Build and publish resume
run-name: Build and publish resume by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - "fonts/**.*"
      - "**.tex"
      - "**.cls"
      - "**.sty"

jobs:
  pdf-generation:
    name: PDF Generation
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
        
      - name: Checking out this updates
        uses: actions/checkout@v3

      - name: Compiling resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          compiler: xelatex
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: resume-${{ github.ref_name }}-${{ env.NOW }}
          release_name: Resume from ${{ github.event.repository.updated_at}} - ${{ github.ref_name }}
          body: |
            Resume from updating  ${{ github.ref_name }} on ${{ github.event.repository.updated_at}}
          draft: false
          prerelease: false
      - name: Upload PDF Release Asset
        id: upload_pdf 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./resume.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf
