name: Build and publish resume
run-name: Build and publish resume by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - "fonts/**.*"
      - "**.tex"
      - "**.cls"
      - "**.sty"

jobs:
  pdf-generation:
    name: PDF Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checking out this updates
        uses: actions/checkout@v3

      - name: Compiling resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          compiler: xelatex
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-resume
          path: resume.pdf
          retention-days: 1
          
  pdf-publish_upload:
    name: PDF Publish
    runs-on: ubuntu-latest
    needs: pdf-generation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: publish
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: my-resume
          
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resume.pdf
          git commit -a -m "generated pdf"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: publish
          force: true
